### ISSUE TITLE
polotno-node doesn't render image properly

### ISSUE THREAD

**Issue by iamsterdam800** [polotno-project/polotno-board#30]
Trying to use polotno-node package for backend automation.
Noticed these bugs in jsonToImageBase64(json, attrs) function:

- setting pixelRatio in attrs does not have effect, because attrs are not passed to store.toDataURL() function
- some images (especially the background) are rendered as white rectangles, because store.waitLoading() returns as soon as the 1st image is loaded?

These (hacky) modifications helped, but would be highly appreciated to have an official fix:
![image](https://user-images.githubusercontent.com/34508588/134061544-fae8bfba-5a09-41f6-9e55-a28774f65506.png)

Additionally, pixelRatio attribute does not seem to scale svg elements. Although handles fonts just fine.
![image](https://user-images.githubusercontent.com/34508588/134064740-155a526d-e3d0-4417-aa7e-dd29332c958b.png)
(svg on the left, text on the right)

**Comment by lavrton** [comment]
> setting pixelRatio in attrs does not have effect, because attrs are not passed to store.toDataURL() function

You are right. It was a bug. It should be fixed now. I published `polotno-node@0.1.12` with the fix.

> some images (especially the background) are rendered as white rectangles, because store.waitLoading() returns as soon as the 1st image is loaded?

There was a bug with loading check for the background. It should be fixed with the last `polotno` version (already included in the last `polotno-node`). I am not sure about other cases with image. Can you check it, please? If you still see the issue, please provide json example.

> Additionally, pixelRatio attribute does not seem to scale svg elements. Although handles fonts just fine.

You are right. It should be fixed now. Please check the last version.

Thanks a lot for the report.

**Comment by iamsterdam800** [comment]
Hi Anton, thanks a lot for the fixes!
I re-tested each issue with v.0.1.12 and everything seems to work perfectly fine!
